#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nginx
Version  : 1.9.5
Release  : 7
URL      : http://nginx.org/download/nginx-1.9.5.tar.gz
Source0  : http://nginx.org/download/nginx-1.9.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: nginx-bin
BuildRequires : openssl-dev
BuildRequires : pcre-dev
BuildRequires : zlib-dev
Patch1: build.patch

%description
Documentation is available at http://nginx.org

%package bin
Summary: bin components for the nginx package.
Group: Binaries

%description bin
bin components for the nginx package.


%prep
%setup -q -n nginx-1.9.5
%patch1 -p1

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/conf/fastcgi.conf
/usr/conf/fastcgi.conf.default
/usr/conf/fastcgi_params
/usr/conf/fastcgi_params.default
/usr/conf/koi-utf
/usr/conf/koi-win
/usr/conf/mime.types
/usr/conf/mime.types.default
/usr/conf/nginx.conf
/usr/conf/nginx.conf.default
/usr/conf/scgi_params
/usr/conf/scgi_params.default
/usr/conf/uwsgi_params
/usr/conf/uwsgi_params.default
/usr/conf/win-utf
/usr/html/50x.html
/usr/html/index.html

%files bin
%defattr(-,root,root,-)
/usr/bin/nginx
